
//******************CLIENT FOR LINK*******************/
/**
 * method type: GET 
 * Get all the links
 * 
 */ 
(async () => {
    const response = await fetch(
        "http://localhost:8080/api/v1/links",
        {
            method: "GET"
        }
    );
    const json = await response.json();
    console.log(json);
})();

/**
 * method type: POST
 * Creates a new link
 * Private end point
 *  
 * */
(async () => {
    
    const data = {
        title: "This is a title example",
        url: "http://averysimpleexampleofanurl/fortheassigment/interactivewebapplications/asmerbracho",
    };
    const response = await fetch(
        "http://localhost:8080/api/v1/links/",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-auth-token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNTQ4OTM0ODk3fQ.4bV2D0D7kzJ50Yp8DaZC0KX8YsRz156MNDlHNU31tvI"
            },
            body: JSON.stringify(data)
        }
    );
    const json = await response.json();
    console.log(json);
})();

/**
 * method type: DELETE
 * DELETE a link
 * Private end point
 *  
 * */
(async () => {
    
    const response = await fetch(
        "http://localhost:8080/api/v1/links/ID_TO_DELETE_HERE",
        {
            method: "DELETE",
            headers: {
                "Content-Type": "application/json",
                "x-auth-token": "<HERE THE TOKEN>"
            },
        }
    );
    const json = await response.json();
    console.log(json);
})();


//******************CLIENT FOR VOTE*******************/
/**
 * method type: POST
 * Upvote Link
 * Private end point
 *  
 * */

(async () => {
    
    const response = await fetch(
        "http://localhost:8080/api/v1/links/<HERE THE ID>/upvote",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-auth-token": "<HERE THE TOKEN>"
            },
        }
    );
    const json = await response.json();
    console.log(json);
})();

//******************CLIENT FOR USER*******************/
/**
 * method type: POST
 * It creates a new User account
 *  
 * */
(async () => {
    
    const data = {
        // ID is autogenerated
        email: "iwa@ca.com",
        password: "12345"
    };
    const response = await fetch(
        "http://localhost:8080/api/v1/users/",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(data)
        }
    );
    const json = await response.json();
    console.log(json);
})();


//******************CLIENT FOR AUTHINTICATION*******************/
/**
 * method type: POST
 * It Logins
 *  
 * */
(async () => {
    const data = {
        email: "iwa@ca.com",
        password: "12345"
    };
    const response = await fetch(
        "http://localhost:8080/api/v1/auth/login/",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(data)
        }
    );
    const json = await response.json();
    console.log(json);
})();

//******************CLIENT FOR COMMENTS*******************/

/**
 * method type: POST
 * Creates a new Comment
 * Private end point
 *  
 * */
(async () => {
    
    const data = {
        text: "This is an example of a comment written by the usser logged in",
        link: {id: 9} 
    };
    const response = await fetch(
        "http://localhost:8080/api/v1/comments/",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "x-auth-token": "<HERE THE TOKEN>"
            },
            body: JSON.stringify(data)
        }
    );
    const json = await response.json();
    console.log(json);
})();


/**
 * method type: PATCH
 * Update a Comment
 * Private end point
 *  
 * */
(async () => {
    
    const data = {
        text: "I am Updating a Comment", 
    };
    const response = await fetch(
        "http://localhost:8080/api/v1/comments/<HERE THE ID OF COMMENT TO BE UPDATED>",
        {
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                "x-auth-token": "<HERE THE TOKEN>"
            },
            body: JSON.stringify(data)
        }
    );
    const json = await response.json();
    console.log(json);
})();


